### ISSUE TITLE
Unknown certificate authority when accessing marmalade-repo.org:443 from 25.1(9.0)

### ISSUE THREAD

**Issue by ghost** [caldwell/build-emacs#58] opened 2017-03-29 19:15 UTC
I'm using version 25.1 (9.0) from emacsformacosx.com and getting the below error when running emacs for the first time on a new machine and accessing the marmalade repo.  But, I do NOT get an error when accessing it from, for example Chrome browser, curl, etc.

This makes me wonder if there is some sort of root cert list embedded in emacs that is out of date?

( This seems related, but wanted to check here first, since this is where the app was packaged: http://emacs.stackexchange.com/questions/18045/how-can-i-retrieve-an-https-url-on-mac-os-x-without-warnings-about-an-untrusted )

---- Network Security Manager ----
Certificate information
Issued by:          COMODO RSA Domain Validation Secure Server CA
Issued to:          Domain Control Validated
Hostname:           marmalade-repo.org
Public key:         RSA, signature: RSA-SHA256
Protocol:           TLS1.2, key: ECDHE-RSA, cipher: AES-256-GCM, mac: AEAD
Security level:     Medium
Valid:              From 2015-07-12 to 2018-07-11

The TLS connection to marmalade-repo.org:443 is insecure for the
following reasons:

the certificate was signed by an unknown and therefore untrusted authority
certificate could not be verified
----

**Comment by caldwell** [comment] 2017-04-04 16:59
What you are seeing happens to everyone. The problem is that Emacs uses the gnutls library and it doesn't have any code to read the Mac OS keychain to get at the root certs. Also it doesn't ship with any root certs. It just assumes there are some lying around in /etc, which isn't the case on the Mac.

One option would be for emacsformacosx.com to include the [Mozilla NSS root cert distribution](https://www.mozilla.org/en-US/about/governance/policies/security-group/certs/) in the Emacs bundle, but that puts me in the position of keeping them up-to-date and broadens the range of security events I have to respond to. So I don't really like that option.

Another options would be to write a script that grabs the roots out of the keychain and sticks them in a directory somewhere that gnutls can read. I like that because it seems easy and self contained, but I don't like the fact that the certs could get out of date. I guess the script could run every time Emacs runs.

The best option would be for gnutls to add support for reading the roots out of the Mac OS keychain. I've contemplated just writing that code myself and submitting it but haven't followed through. I'm not sure if the patch would be appreciated… maybe I should just ask them.

**Comment by tzz** [comment] 2017-04-04 18:33
@caldwell I would support such a C patch against GnuTLS. Emacs uses `gnutls_certificate_set_x509_system_trust()` which should be fixed from the GnuTLS side.

But if you want a workaround in the meanwhile, we could write a GNU ELPA package that will grab the root certificates from the Mac OS keychain on Emacs startup, then augments `gnutls-trustfiles`, and users can install it.

**Comment by caldwell** [comment] 2017-04-05 19:42
@tzz FYI, https://gitlab.com/gnutls/gnutls/merge_requests/342

**Comment by caldwell** [comment] 2018-05-30 17:30
The merge request was accepted by gnutls a long time ago and the Emacs builds no longer complain about certificate authorities (for valid certs).

**Closed by caldwell** 2018-05-30 17:30 UTC
