### ISSUE TITLE
helm-projectile crashes/breaks emacs on Mac OS X

### ISSUE THREAD

**Issue by noorul** [caldwell/build-emacs#40] opened 2015-03-03 17:45 UTC
The following has details

https://github.com/bbatsov/projectile/issues/600

**Comment by caldwell** [comment] 2015-03-03 21:11
This appears to be fixed in the latest Emacs versions? Both the emacs bugs referenced in that thread were fixed by Jan D. They should be available on the [the builds page](http://emacsformacosx.com/builds). The Emacs 25 branch is the "Nightly" code and the latest 24 branch code is the "Pretest".
At any rate, none of those crashing bugs are caused by the build script itself (as far as I can tell, and correct me if I'm wrong), so I'm closing this bug.

**Closed by caldwell** 2015-03-03 21:11 UTC

**Comment by noorul** [comment] 2015-03-04 02:06
I agree with you that the issue is not with the build script. But do you think http://emacsformacosx.com/emacs-builds/Emacs-24.4-universal.dmg should point to bug free version?

**Comment by caldwell** [comment] 2015-03-04 02:40
No, because [Emacs-24.4-universal.dmg](http://emacsformacosx.com/emacs-builds/Emacs-24.4-universal.dmg) is the binary build of [emacs-24.4.tar.xz](http://psg.mtu.edu/pub/gnu/emacs/emacs-24.4.tar.xz), which sadly includes the bug.

EmacsForMacOSX.com doesn't maintain its own source for Emacs, it merely provides builds of the official Emacs releases (as well as nightly builds of the official git repository).

It is regrettable when there is such a bug in an Emacs release, but in the meantime there is a pretest that was released a couple weeks ago which should contain the fix (2015-02-17—I think that was after the fix was applied to the 24 branch). On the upside, it appears as if they are going to get a 24.5 release of fairly soon.
