### ISSUE TITLE
ispell don't work out of the box

### ISSUE THREAD

**Issue by Lindydancer** [caldwell/build-emacs#35] opened 2014-11-11 20:16 UTC
When starting Emacs by double-clicking, the directory where "aspell" is located (/usr/local/bin) is not in the exec path. This cause ispell to fail to find the aspell executable, see ispell-program-name for details.

When started from the command-line, however, it is.

I don't know if this is a "emacsforosx" problem or a problem with Emacs itself, feel free to report this upstream if you think it's appropriate.

    -- Anders

**Comment by zbeekman** [comment] 2015-02-04 19:09
I would love to know if this is an Emacs bug or a build bug…

**Comment by caldwell** [comment] 2015-02-11 22:16
Do you manipulate the exec-path in your .emacs? Try launching with -Q:

    open /Application/Emacs.app --args -Q

and then let me know what your exec-path is. Are you running on Yosemite (10.10)? This might be related to a bug I just found in Yosemite (#39)…

**Comment by radford** [comment] 2015-03-02 21:48
I can confirm that this is caused by the multiple-```PATH```s-issue on Yosemite and that 6b63ede3 fixes it.

**Comment by caldwell** [comment] 2015-05-12 17:43
Thanks, @radford. Closing.

**Closed by caldwell** 2015-05-12 17:43 UTC
