### ISSUE TITLE
Emacs 26.0.91-1 crash when using TLS libraries

### ISSUE THREAD

**Issue by Lindydancer** [caldwell/build-emacs#67] opened 2018-02-05 20:43 UTC
Hi!

I just downloaded 26.0.91-1 (the repacked version with a signed TLS library). When I launch Emacs and run something like `package-refresh-contents`, it crashes with what appears to a problem in the GNUTLS libraries.

I use an eight core Mac Pro 2008 running 10.10.5 (Yosemite).

I've attached the macOS crash log, as a plain text file.

[Emacs26crash.txt](https://github.com/caldwell/build-emacs/files/1696698/Emacs26crash.txt)

Sincerely,
    Anders Lindgren (former Emacs NS-port maintainer)

**Comment by NateEag** [comment] 2018-02-27 15:23
This looks like a duplicate of #60.

Maybe see if [this workaround](https://github.com/caldwell/build-emacs/issues/60#issuecomment-327835428) works for you?

**Comment by Lindydancer** [comment] 2018-02-27 16:15
No, it's not, since I have no problems running 25.2 from www.emacsforosx.com on my machine.

I already have a workaround (building Emacs for sources) -- I reported so that it can be fixed before Emacs 26 is released, when I suspect a large number of people will download Emacs.

    -- Anders

**Comment by NateEag** [comment] 2018-02-27 21:31
Ah, okay. Makes sense.

**Comment by ferfebles** [comment] 2018-05-30 09:12
Same here with Emacs 26.1 running in a MacBook Pro Mid2010 with HighSierra 10.13.4.

Solved by uninstalling/reinstalling homebrew and then using [the commented workaround](https://github.com/caldwell/build-emacs/issues/60#issuecomment-327835428) with the two libgnutls.30.dylib that I found.

```
mv /Applications/Emacs.app/Contents/MacOS/lib-x86_64-10_10/libgnutls.30.dylib libgnutls.30.dylib_10
mv /Applications/Emacs.app/Contents/MacOS/lib-x86_64-10_9/libgnutls.30.dylib libgnutls.30.dylib_10
brew install gnutls
```
After that I can install packages with Emacs26.1.

(Perhaps reinstalling homebrew is not needed, but I did that before trying the workaround )

**Comment by Lindydancer** [comment] 2018-05-30 11:02
Hi,

I'm glad you got it working with the workaround.

However, I'm still hoping for a solution where Emacs would work out of the
box. Installing Brew is not something that all Mac users is comfortable
with, or is even allowed to do.

    -- Anders

**Closed** 2018-05-31 02:32 UTC
