### ISSUE TITLE
Strange image artifact on El Capitan (10.11.1)

### ISSUE THREAD

**Issue by jsquyres** [caldwell/build-emacs#46] opened 2015-11-04 22:29 UTC
I just downloaded and installed v24.5.1.  When I do a search and don't find anything, I get a strange visual artifact in the middle of the emacs window:

![2015-11-04_1727-emacs-oddity](https://cloud.githubusercontent.com/assets/617316/10954115/97430952-8319-11e5-81f4-25054836b901.png)

Any idea what this is / how to fix it?

**Comment by rakkesh** [comment] 2015-11-21 03:50
It seems to me that `visible-bell` is enabled, this is by default off. Check for it in your emacs startup file and try removing it.

**Comment by jsquyres** [comment] 2015-11-21 03:54
Yes, true -- it is enabled.  And disabling it avoids the problem.

But that doesn't solve the actual problem...

**Comment by rakkesh** [comment] 2015-11-21 04:30
Yes, sorry. I build emacs from git every 2-3 weeks. I started seeing this problem about over a month back but never checked when this was introduced. Recently, I have been using [emacs-macport](https://github.com/railwaycat/mirror-emacs-mac) which flashes `mini-buffer` and top of the buffer when `visible-bell` is enabled.

**Comment by caldwell** [comment] 2015-11-21 05:07
Thanks for tracking it to visible-bell! I've had others report similar things but could never reproduce it locally. I'll forward this on to the main emacs bug tracker (this one is just for bugs in the build scripts themselves).

**Comment by caldwell** [comment] 2015-11-21 20:49
[I filed this report with Emacs](http://debbugs.gnu.org/cgi/bugreport.cgi?bug=21977) and so I'm going close this bug. You might check the bug I filed out since I uncovered more dirt on what is going on.

**Closed by caldwell** 2015-11-21 20:49 UTC

**Comment by rakkesh** [comment] 2015-11-22 08:00
👍 for the bug report.
